server:
  port: 1000

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/local
---
spring:
  config:
    activate:
      on-profile: production
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bettor-league/configuration-repository
          default-label: develop