logging:
  level:
    org.springframework.security: DEBUG

security:
  enabled: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bettor-league


---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongo-database