server.port: 0


bettor-league:
  user:
    admin:
      id: 4b4f822e-eb69-432e-be30-c2f4b156523d
      email: ${BETTOR_LEAGUE_ADMIN_EMAIL}
      password: ${BETTOR_LEAGUE_ADMIN_PASSWORD}
  client:
    ui:
      id: ${BETTOR_LEAGUE_CLIENT_UI_ID}
      secret: ${BETTOR_LEAGUE_CLIENT_UI_SECRET}
      scope:
        - read
    swagger:
      id: ${BETTOR_LEAGUE_CLIENT_SWAGGER_ID}
      secret: ${BETTOR_LEAGUE_CLIENT_SWAGGER_SECRET}
      scope:
        - read
    server:
      id: ${BETTOR_LEAGUE_CLIENT_SERVER_ID}
      secret: ${BETTOR_LEAGUE_CLIENT_SERVER_SECRET}
      scope:
        - read
        - write
# SWAGGER
springdoc:
  swagger-ui:
    use-root-path: true
    oauth:
      use-basic-authentication-with-access-code-grant: true
      client-id: ${BETTOR_LEAGUE_CLIENT_SWAGGER_ID}
      client-secret: ${BETTOR_LEAGUE_CLIENT_SWAGGER_SECRET}
  oauth-flow:
    authorization-url: http://localhost:5000/oauth2/authorize
    token-url: http://localhost:5000/oauth2/token

# Spring
spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:5000
      client:
        registration:
          server-client:
            provider: spring
            client-id: ${BETTOR_LEAGUE_CLIENT_SERVER_ID}
            client-secret: ${BETTOR_LEAGUE_CLIENT_SERVER_SECRET}
            authorization-grant-type: client_credentials
            scope:
              - read
              - write
            client-name: server-client
        provider:
          spring:
            token-uri: http://localhost:5000/oauth2/token

# Actuator
management:
  endpoint:
    env:
      show-values: WHEN_AUTHORIZED
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

# Eureka
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/

# Security
security:
  enabled: true
  unprotected-path:
    - /
    - /error
    - /favicon.ico
    - /*/*.png
    - /*/*.gif
    - /*/*.svg
    - /*/*.jpg
    - /*/*.html
    - /*/*.css
    - /*/*.js
    - /*/*.js.map
    - /actuator/**
    - /v3/api-docs
    - /v3/api-docs/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger-ui/**
    - /webjars/**
    - /assets/**
    - /csrf
    - /oauth/**
    - /oauth2/**
    - /authentication
    - /login
    - /logout

# Football-data.org
football-data:
  base-url: http://api.football-data.org
  competitions: 2002,2014,2015,2019,2021,2003,2013
  tokens: ${BETTOR_LEAGUE_FOOTBALL_DATA_TOKENS}

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:2000/eureka/
