# Start services on random port by default
server.port: 0

# SWAGGER
springdoc:
  swagger-ui:
    use-root-path: true
    oauth:
      use-basic-authentication-with-access-code-grant: true
      client-id: bettor-league-swagger
      client-secret: ${BETTOR_LEAGUE_SWAGGER_SECRET}
  oauth-flow:
    authorization-url: http://localhost:5000/oauth2/authorize
    token-url: http://localhost:5000/oauth2/token

# Spring
spring:
  profiles:
    active: development
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:5000
      client:
        registration:
          server-client:
            provider: spring
            client-id: bettor-league-server
            client-secret: ${BETTOR_LEAGUE_SERVER_SECRET}
            authorization-grant-type: client_credentials
            scope: server
            client-name: server-client
        provider:
          spring:
            token-uri: http://localhost:5000

# Actuator
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/

# Security
security:
  enabled: true
  unprotected-path:
    - /
    - /error
    - /favicon.ico
    - /swagger-ui.html
    - /**/*.png
    - /**/*.gif
    - /**/*.svg
    - /**/*.jpg
    - /**/*.html
    - /**/*.css
    - /**/*.js
    - /**/*.js.map
    - /actuator/**
    - /v3/api-docs/**
    - /swagger-resources/**
    - /swagger-ui/**
    - /webjars/**
    - /oauth/**
    - /oauth2/**
    - /authentication
    - /login
    - /logout


---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:2000/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://authentication-service:5000/oauth/me
      token-info-uri: http://authentication-service:5000/oauth/check_token
    client:
      accessTokenUri: http://authentication-service:5000/oauth/token