server:
  port: 5000

bettorleague:
  oauth2:
    client:
      ui:
        client-id: bettor-league-ui
        client-secret: BETTOR_LEAGUE_CLIENT_PASSWORD
      server:
        client-id: bettor-league-server
        client-secret: BETTOR_LEAGUE_SERVER_PASSWORD
security:
  social: true
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bettor-league
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 983464398033-vgjunh6qcpbs9riprq99u46gjq7kbmcq.apps.googleusercontent.com
            client-secret: uVghPcBz66tey9T_2VRF6v0p
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            client-id: 360218771245694
            client-secret: 6583919fb824ed6d737791a24e87dbfb
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
---
spring:
  profiles: docker
  data:
    mongodb:
      host: mongo-database