server:
  port: 4000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods: '*'
            allowed-headers: '*'
            allow-credentials: true
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
          - Path=/api/admin-service/**
          filters:
          - StripPrefix=2
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
          - Path=/api/authentication-service/**
          filters:
          - StripPrefix=2
        - id: account-service
          uri: lb://account-service
          predicates:
          - Path=/api/account-service/**
          filters:
          - StripPrefix=2
        - id: open-api
          uri: http://localhost:${server.port}
          predicates:
          - Path=/v3/api-docs/**
          filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /api/$\{path}/v3/api-docs