server:
  port: 4000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/authentication-service/**
          filters:
            - StripPrefix=2
        - id: account-query-service
          uri: lb://account-query-service
          predicates:
            - Path=/api/account-query-service/**
          filters:
            - StripPrefix=2

springdoc:
  swagger-ui:
    urls:
      - name: authentication-service
        url: /api/authentication-service/v3/api-docs
      - name: account-query-service
        url: /api/account-query-service/v3/api-docs