name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: mvn clean install -s .github/workflows/settings.xml
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: mvn deploy -s .github/workflows/settings.xml